from selenium.webdriver.chrome.options import Options
import time
from helper.pages.base import *

driver = webdriver.Chrome()
driver.set_window_position(2000, 600)
option = Options()
option.add_argument("--start-maximized")
prefs = {"profile.default_content_setting_values.notifications": 1}
option.add_experimental_option("prefs", prefs)
driver = webdriver.Chrome(options=option)

url = 'https://killa.com.ua/'
driver.get(url)

print(driver.get_cookies())

home = BasePage(driver)
time.sleep(5)
home.open_about()
time.sleep(5)
home.open_delivery_and_payment()
time.sleep(5)
home.open_refund_replacement()
time.sleep(5)
home.open_contacts()
time.sleep(5)
home.open_helps()
time.sleep(5)
home.open_feedbacks()
time.sleep(5)
home.open_dropshipping()
time.sleep(5)
home.open_categories()
home.open_categories_new_products()
time.sleep(5)
home.open_categories()
home.open_categories_tactical_clothing()
time.sleep(5)
home.open_categories()
home.open_categories_tactical_shoes()
time.sleep(5)
home.open_categories()
home.open_categories_tourism_camping()
time.sleep(5)
home.open_categories()
home.open_categories_military_equipment()
time.sleep(5)
home.open_categories()
home.open_categories_tactical_equipment()
time.sleep(5)
home.open_categories()
home.open_categories_components()
time.sleep(5)
home.open_categories()
home.open_categories_optics()
time.sleep(5)
home.open_categories()
home.open_categories_backpacks()
time.sleep(5)
home.open_categories()
home.open_categories_fishing_and_hunting()
time.sleep(5)
home.open_categories()
home.open_categories_trainers()
home.open_homepage()
time.sleep(5)
print(driver.get_cookies())
time.sleep(300)
